name: pull_to_refresh
description: a widget provided to the flutter scroll component drop-down refresh and pull up load.
version: 1.5.5
author: Jpeng <peng8350@gmail.com>
homepage: https://github.com/peng8350/flutter_pulltorefresh

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  #flutter:
  #  sdk: flutter
  flutter_web: any
  flutter_web_ui: any
  test: ^1.3.4

dev_dependencies:
  flutter_web_test: any
  #flutter_test:
  #  sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test